[build]
  # Base directory for build - this is the root of the monorepo
  base = "."
  # Build command for the frontend - enable browser-only mode with VITE_WITH_CORE
  command = "VITE_WITH_CORE=true pnpm run packages:build && VITE_WITH_CORE=true pnpm run web:build"
  # Publish directory - where the built static files are located
  publish = "apps/web/dist"
  # Functions directory - where the serverless functions are located
  functions = "netlify/functions"

# Environment variables for build
[build.environment]
  NODE_VERSION = "22.20.0"
  PNPM_VERSION = "10.17.1"
  # Enable browser-only mode by default (use PGlite instead of backend server)
  # Set to false to use PostgreSQL backend
  VITE_WITH_CORE = "true"
  # Telegram API credentials
  VITE_TELEGRAM_APP_ID = "611335"
  VITE_TELEGRAM_APP_HASH = "d524b414d21f4d37f08684c1df41ac9c"
  # Database configuration (optional - set in Netlify UI for production)
  # DATABASE_TYPE = "postgres"  # Set to "postgres" to use PostgreSQL backend
  # DATABASE_URL = "postgresql://user:password@host:port/database"  # PostgreSQL connection string

# Functions configuration
[functions]
  # Use esbuild for bundling functions (required for workspace dependencies)
  node_bundler = "esbuild"
  # Include all node_modules in the bundle
  included_files = ["node_modules/**", "packages/*/dist/**", "packages/*/src/**"]

# Redirect API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Redirect API v1 calls to the new API function
[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Redirect WebSocket connections to the serverless function (polling-based)
[[redirects]]
  from = "/ws"
  to = "/.netlify/functions/ws"
  status = 200
  force = true

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS and security
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cache-Control, X-Requested-With"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

# Headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cache-Control, X-Requested-With"
    Access-Control-Allow-Credentials = "true"

# Headers for WebSocket
[[headers]]
  for = "/ws"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cache-Control, X-Requested-With, Upgrade, Connection"
    Access-Control-Allow-Credentials = "true"
