[build]
  # Build command for the frontend - enable browser-only mode with VITE_WITH_CORE
  command = "VITE_WITH_CORE=true pnpm run packages:build && VITE_WITH_CORE=true pnpm run web:build"
  # Publish directory - where the built static files are located
  publish = "apps/web/dist"
  # Functions directory - where the serverless functions are located
  functions = "netlify/functions"

# Environment variables for build
[build.environment]
  NODE_VERSION = "22.20.0"
  PNPM_VERSION = "10.17.1"
  # Enable browser-only mode (use PGlite instead of backend server)
  VITE_WITH_CORE = "true"
  # Telegram API credentials
  VITE_TELEGRAM_APP_ID = "611335"
  VITE_TELEGRAM_APP_HASH = "d524b414d21f4d37f08684c1df41ac9c"

# Redirect API calls to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Redirect WebSocket connections to the serverless function
[[redirects]]
  from = "/ws"
  to = "/.netlify/functions/ws"
  status = 200
  force = true

# SPA fallback - redirect all other requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS and security
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cache-Control, X-Requested-With"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

# Headers for API endpoints
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cache-Control, X-Requested-With"
    Access-Control-Allow-Credentials = "true"

# Headers for WebSocket
[[headers]]
  for = "/ws"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Cache-Control, X-Requested-With, Upgrade, Connection"
    Access-Control-Allow-Credentials = "true"
