[build]
  base = "/"
  command = "pnpm run db:migrate && pnpm run build"
  publish = "apps/web/dist"
  functions = "apps/server/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
